### ISSUE TITLE
Incompatibility with Gunpowder

### ISSUE THREAD

**Issue by DevEkode** [DevEkode/FabricLockette#19]
**Describe the bug**
Issue with Gunpowder fabric mod causing to FabricLockette to malfunction (no crash)

Opened after the following discussion on #16 issue :

>Despite having this error on the console, the sign protects correctly the chests and the doors from other players. The text in the first line of the letter doesn't get bold.
The text of the sign with [Private] only seems visible to the person who protected.

> Ok, thx for the confirmation. After a lot of painful try and error, i found the incompatibility. It is with the mod Gunpowder 0.5.7 (the latest version for 1.16).

**To Reproduce**
1. Load a Fabric server with the list of mods in "Environnement version" section.
2. Add [Private] sign on chest.
4. See error in console (see Additional context)

**Expected behavior**
No errors in console and [Private] visible to others users.

**Environnement versions:**
* fabric-api-0.39.1+1.16
* fabric-language-kotlin-1.6.1+kotlin.1.5.10
* FabricLockette-mc1.16.x-0.1.0-dev.1+develop.7cbd32f
* gunpowder-base-0.5.7+1.16.5

**Additional context**
```
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:Private
        at net.minecraft.class_2960.<init>(class_2960.java:41) ~[intermediary-server.jar:?]
        at net.minecraft.class_2960.<init>(class_2960.java:46) ~[intermediary-server.jar:?]
        at net.minecraft.class_2625.method_5431(class_2625.java:1112) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31282(class_3244.java:1501) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31285(class_3244.java:1476) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31284(class_3244.java:314) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31280(class_3244.java:324) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by DevEkode** [comment]
Using IntelliJ, I managed to get a non obfuscated stack trace of the error :
```
net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: minecraft:Private
	at net.minecraft.util.Identifier.<init>(Identifier.java:41) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.Identifier.<init>(Identifier.java:46) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.block.entity.SignBlockEntity.markDirty(SignBlockEntity.java:1112) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_31282(ServerPlayNetworkHandler.java:1501) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_31285(ServerPlayNetworkHandler.java:1476) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_31284(ServerPlayNetworkHandler.java:314) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_31280(ServerPlayNetworkHandler.java:324) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:144) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:761) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:155) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:118) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:737) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:127) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
